export const INTERVIEW_STATES = {
  IDLE: 'IDLE',
  AI_SPEAKING: 'AI_SPEAKING',
  USER_SPEAKING: 'USER_SPEAKING',
  AI_ANALYZING: 'AI_ANALYZING',
  INTERVIEW_COMPLETE: 'INTERVIEW_COMPLETE',
}

export const STATE_LABELS = {
  [INTERVIEW_STATES.IDLE]: 'standby',
  [INTERVIEW_STATES.AI_SPEAKING]: 'ai_speaking',
  [INTERVIEW_STATES.USER_SPEAKING]: 'user_speaking',
  [INTERVIEW_STATES.AI_ANALYZING]: 'ai_analyzing',
  [INTERVIEW_STATES.INTERVIEW_COMPLETE]: 'interview_complete',
}
